@FribergRealEstatesAPI_HostAddress = http://localhost:5170

GET {{FribergRealEstatesAPI_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{FribergRealEstatesAPI_HostAddress}}/api/Address/12
Accept: application/json
